# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities =: City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#############################################################################
# DWARF ANGELS
#############################################################################
Fish.create( 
      name: "Dwarf Angels", 
      wiki_url: 'Centropyge',
      dwarf_angels: "C",
      large_angels:  "Y",
      anglers_frogs: "C",
      anthias: "Y",
      basslets: "Y",
      batfish: "Y",
      blennies: "Y",
      boxfish: "Y",
      butterflies: "Y",
      cardinals: "Y",
      chromis: "Y",
      clownfish: "Y",
      damsels: "Y",
      dartfish: "Y",
      dragonets: "Y",
      eels: "C",
      filefish: "Y",
      foxface_rabbits: "Y",
      gobies: "Y",
      groupers: "C",
      grunts_sweetlips: "Y",
      jawfish: "Y",
      hawkfish: "Y",
      hogfish: "Y",
      lions_scorpions: "C",
      parrotfish: "Y",
      pseudochromis: "Y",
      puffers: "Y",
      seahorse_pipefish: "N",
      sharks_rays: "N",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish: "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals: "C",
      invertebrates: "C",
      live_rock_sand: "Y"
      )

#############################################################################
# LARGE ANGELS
#############################################################################
Fish.create( 
      name: "Large Angels",
      wiki_url: 'Pomacanthidae',
      dwarf_angels: "Y",
      large_angels: "C",
      anglers_frogs:  "Y",
      anthias:  "Y",
      basslets: "Y",
      batfish:  "Y",
      blennies: "Y",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "C",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "Y",
      dartfish: "C",
      dragonets:  "Y",
      eels: "Y",
      filefish: "C",
      foxface_rabbits:  "Y",
      gobies: "C",
      groupers: "Y",
      grunts_sweetlips: "Y",
      jawfish:  "C",
      hawkfish: "Y",
      hogfish:  "Y",
      lions_scorpions:  "Y",
      parrotfish: "Y",
      pseudochromis:  "C",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "C",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "Y",
      live_corals:  "C",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# ANGLERS/FROGS
#############################################################################
Fish.create( 
      name: "Anglers/Frogs",
      wiki_url: 'Frogfish',
      dwarf_angels: "C",
      large_angels: "Y",
      anglers_frogs:  "C",
      anthias:  "C",
      basslets: "N",
      batfish:  "Y",
      blennies: "N",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "N",
      chromis:  "N",
      clownfish:  "N",
      damsels:  "N",
      dartfish: "N",
      dragonets:  "N",
      eels: "C",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "N",
      groupers: "C",
      grunts_sweetlips: "Y",
      jawfish:  "N",
      hawkfish: "C",
      hogfish:  "C",
      lions_scorpions:  "Y",
      parrotfish: "C",
      pseudochromis:  "N",
      puffers:  "C",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "N",
      wrasse_reef_safe: "C",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# ANTHIAS
#############################################################################
Fish.create( 
      name: "Anthias",
      wiki_url: 'Anthiinae',
      dwarf_angels: "Y",
      large_angels: "Y",
      anglers_frogs:  "C",
      anthias:  "C",
      basslets: "Y",
      batfish:  "C",
      blennies: "Y",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "Y",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "Y",
      dartfish: "Y",
      dragonets:  "Y",
      eels: "C",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "N",
      grunts_sweetlips: "Y",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "Y",
      lions_scorpions:  "C",
      parrotfish: "Y",
      pseudochromis:  "Y",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# BASSLETS
#############################################################################
Fish.create( 
      name: "Basslets",
      wiki_url: 'Grammatidae',
      dwarf_angels: "Y",
      large_angels: "Y",
      anglers_frogs:  "N",
      anthias:  "Y",
      basslets: "N",
      batfish:  "C",
      blennies: "C",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "Y",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "Y",
      dartfish: "C",
      dragonets:  "C",
      eels: "N",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "N",
      grunts_sweetlips: "Y",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "C",
      lions_scorpions:  "N",
      parrotfish: "C",
      pseudochromis:  "N",
      puffers:  "C",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "N",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# BATFISH
#############################################################################
Fish.create( 
      name: "Batfish",
      wiki_url: 'Ephippidae',
      dwarf_angels: "Y",
      large_angels: "Y",
      anglers_frogs:  "Y",
      anthias:  "C",
      basslets: "C",
      batfish:  "N",
      blennies: "C",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "Y",
      chromis:  "C",
      clownfish:  "Y",
      damsels:  "C",
      dartfish: "C",
      dragonets:  "C",
      eels: "C",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "N",
      grunts_sweetlips: "Y",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "C",
      lions_scorpions:  "C",
      parrotfish: "Y",
      pseudochromis:  "C",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "Y",
      tangs_surgeons: "C",
      triggerfish:  "N",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# BLENNIES
#############################################################################
Fish.create( 
      name: "Blennies",
      wiki_url: 'Blennioidei',
      dwarf_angels: "Y",
      large_angels: "Y",
      anglers_frogs:  "N",
      anthias:  "Y",
      basslets: "C",
      batfish:  "C",
      blennies: "C",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "C",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "Y",
      dartfish: "Y",
      dragonets:  "C",
      eels: "N",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "N",
      grunts_sweetlips: "C",
      jawfish:  "C",
      hawkfish: "Y",
      hogfish:  "C",
      lions_scorpions:  "N",
      parrotfish: "C",
      pseudochromis:  "C",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "C",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# BOXFISH
#############################################################################
Fish.create( 
      name: "Boxfish",
      wiki_url: 'Ostraciidae',
      dwarf_angels:  "Y",
      large_angels: "Y",
      anglers_frogs:  "Y",
      anthias:  "Y",
      basslets: "Y",
      batfish:  "Y",
      blennies: "Y",
      boxfish:  "C",
      butterflies:  "Y",
      cardinals:  "Y",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "Y",
      dartfish: "Y",
      dragonets:  "Y",
      eels: "Y",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "C",
      grunts_sweetlips: "Y",
      jawfish:  "Y",
      hawkfish: "C",
      hogfish:  "Y",
      lions_scorpions:  "Y",
      parrotfish: "Y",
      pseudochromis:  "Y",
      puffers:  "C",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "Y",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# BUTTERFLIES
#############################################################################
Fish.create( 
      name: "Butterflies",
      wiki_url: 'Butterflyfish',
      dwarf_angels: "Y",
      large_angels: "Y",
      anglers_frogs:  "Y",
      anthias:  "Y",
      basslets: "Y",
      batfish:  "Y",
      blennies: "Y",
      boxfish:  "Y",
      butterflies:  "C",
      cardinals:  "Y",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "Y",
      dartfish: "Y",
      dragonets:  "Y",
      eels: "C",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "C",
      grunts_sweetlips: "Y",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "Y",
      lions_scorpions:  "C",
      parrotfish: "Y",
      pseudochromis:  "Y",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "C",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "C",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# CARDINALS
#############################################################################
Fish.create( 
      name: "Cardinals",
      wiki_url: 'Apogonidae',
      dwarf_angels: "Y",
      large_angels: "C",
      anglers_frogs:  "N",
      anthias:  "Y",
      basslets: "Y",
      batfish:  "Y",
      blennies: "C",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "Y",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "C",
      dartfish: "Y",
      dragonets:  "Y",
      eels: "N",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "N",
      grunts_sweetlips: "Y",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "C",
      lions_scorpions:  "N",
      parrotfish: "C",
      pseudochromis:  "C",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "C",
      tangs_surgeons: "Y",
      triggerfish:  "N",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# CHROMIS
#############################################################################
Fish.create( 
      name: "Chromis",
      wiki_url: 'Chromis',
      dwarf_angels: "Y",
      large_angels: "Y",
      anglers_frogs:  "N",
      anthias:  "Y",
      basslets: "Y",
      batfish:  "C",
      blennies: "Y",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "Y",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "C",
      dartfish: "Y",
      dragonets:  "Y",
      eels: "N",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "N",
      grunts_sweetlips: "C",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "C",
      lions_scorpions:  "N",
      parrotfish: "Y",
      pseudochromis:  "Y",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "C",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# CLOWNFISH
#############################################################################
Fish.create( 
      name: "Clownfish",
      wiki_url: 'Amphiprioninae',
      dwarf_angels: "Y",
      large_angels: "Y",
      anglers_frogs:  "N",
      anthias:  "Y",
      basslets: "Y",
      batfish:  "Y",
      blennies: "Y",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "Y",
      chromis:  "Y",
      clownfish:  "C",
      damsels:  "Y",
      dartfish: "Y",
      dragonets:  "Y",
      eels: "N",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "N",
      grunts_sweetlips: "Y",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "C",
      lions_scorpions:  "N",
      parrotfish: "Y",
      pseudochromis:  "Y",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "Y",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# DAMSELS
#############################################################################
Fish.create( 
      name: "Damsels",
      wiki_url: 'Damselfish',
      dwarf_angels: "Y",
      large_angels: "Y",
      anglers_frogs:  "N",
      anthias:  "Y",
      basslets: "Y",
      batfish:  "C",
      blennies: "Y",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "C",
      chromis:  "C",
      clownfish:  "Y",
      damsels:  "C",
      dartfish: "C",
      dragonets:  "Y",
      eels: "N",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "N",
      grunts_sweetlips: "C",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "C",
      lions_scorpions:  "N",
      parrotfish: "Y",
      pseudochromis:  "Y",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "C",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "Y",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# DARTFISH
#############################################################################
Fish.create( 
      name: "Dartfish",
      wiki_url: 'Dartfish',
      dwarf_angels: "Y",
      large_angels: "C",
      anglers_frogs:  "N",
      anthias:  "Y",
      basslets: "C",
      batfish:  "C",
      blennies: "Y",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "Y",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "C",
      dartfish: "C",
      dragonets:  "Y",
      eels: "N",
      filefish: "C",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "N",
      grunts_sweetlips: "C",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "C",
      lions_scorpions:  "N",
      parrotfish: "C",
      pseudochromis:  "C",
      puffers:  "C",
      seahorse_pipefish:  "C",
      sharks_rays:  "N",
      squirrelfish: "C",
      tangs_surgeons: "Y",
      triggerfish:  "N",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# DRAGONETS
#############################################################################
Fish.create( 
      name: "Dragonets",
      wiki_url: 'Dragonet',
      dwarf_angels: "Y",
      large_angels: "Y",
      anglers_frogs:  "N",
      anthias:  "Y",
      basslets: "C",
      batfish:  "C",
      blennies: "C",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "Y",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "Y",
      dartfish: "Y",
      dragonets:  "C",
      eels: "N",
      filefish: "C",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "N",
      grunts_sweetlips: "C",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "C",
      lions_scorpions:  "N",
      parrotfish: "C",
      pseudochromis:  "C",
      puffers:  "Y",
      seahorse_pipefish:  "Y",
      sharks_rays:  "N",
      squirrelfish: "C",
      tangs_surgeons: "Y",
      triggerfish:  "N",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# Eels
#############################################################################
Fish.create( 
      name: "Eels",
      wiki_url: 'Moray_eel',
      dwarf_angels: "C",
      large_angels: "Y",
      anglers_frogs:  "C",
      anthias:  "C",
      basslets: "N",
      batfish:  "C",
      blennies: "N",
      boxfish:  "Y",
      butterflies:  "C",
      cardinals:  "N",
      chromis:  "N",
      clownfish:  "N",
      damsels:  "N",
      dartfish: "N",
      dragonets:  "N",
      eels: "C",
      filefish: "N",
      foxface_rabbits:  "C",
      gobies: "N",
      groupers: "C",
      grunts_sweetlips: "Y",
      jawfish:  "N",
      hawkfish: "N",
      hogfish:  "C",
      lions_scorpions:  "Y",
      parrotfish: "C",
      pseudochromis:  "N",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "C",
      squirrelfish: "C",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "C",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# FILEFISH
#############################################################################
Fish.create( 
      name: "Filefish",
      wiki_url: 'Filefish',
      dwarf_angels: "Y",
      large_angels: "C",
      anglers_frogs:  "Y",
      anthias:  "Y",
      basslets: "Y",
      batfish:  "Y",
      blennies: "Y",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "Y",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "Y",
      dartfish: "C",
      dragonets:  "C",
      eels: "N",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "N",
      grunts_sweetlips: "Y",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "Y",
      lions_scorpions:  "C",
      parrotfish: "Y",
      pseudochromis:  "C",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "N",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "C",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# FOXFACE/RABBITS
#############################################################################
Fish.create( 
      name: "Foxface/Rabbits",
      wiki_url: 'Foxface_rabbitfish',
      dwarf_angels: "Y",
      large_angels: "Y",
      anglers_frogs:  "Y",
      anthias:  "Y",
      basslets: "Y",
      batfish:  "Y",
      blennies: "Y",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "Y",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "Y",
      dartfish: "Y",
      dragonets:  "Y",
      eels: "C",
      filefish: "Y",
      foxface_rabbits:  "C",
      gobies: "Y",
      groupers: "Y",
      grunts_sweetlips: "Y",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "Y",
      lions_scorpions:  "Y",
      parrotfish: "Y",
      pseudochromis:  "Y",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "C",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "C",
      invertebrates:  "C",
      live_rock_sand: "Y",
      )

#############################################################################
# GOBIES
#############################################################################
Fish.create( 
      name: "Gobies",
      wiki_url: 'Goby',
      dwarf_angels: "Y",
      large_angels: "C",
      anglers_frogs:  "N",
      anthias:  "Y",
      basslets: "Y",
      batfish:  "Y",
      blennies: "Y",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "Y",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "Y",
      dartfish: "Y",
      dragonets:  "Y",
      eels: "N",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "C",
      groupers: "N",
      grunts_sweetlips: "C",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "C",
      lions_scorpions:  "N",
      parrotfish: "C",
      pseudochromis:  "Y",
      puffers:  "Y",
      seahorse_pipefish:  "C",
      sharks_rays:  "N",
      squirrelfish: "C",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "N",
      live_rock_sand: "Y"
      )

#############################################################################
# GROUPERS
#############################################################################
Fish.create( 
      name: "Groupers",
      wiki_url: 'Grouper',
      dwarf_angels: "C",
      large_angels: "Y",
      anglers_frogs:  "C",
      anthias:  "N",
      basslets: "N",
      batfish:  "N",
      blennies: "N",
      boxfish:  "C",
      butterflies:  "C",
      cardinals:  "N",
      chromis:  "N",
      clownfish:  "N",
      damsels:  "N",
      dartfish: "N",
      dragonets:  "N",
      eels: "C",
      filefish: "N",
      foxface_rabbits:  "Y",
      gobies: "N",
      groupers: "N",
      grunts_sweetlips: "C",
      jawfish:  "N",
      hawkfish: "N",
      hogfish:  "C",
      lions_scorpions:  "Y",
      parrotfish: "C",
      pseudochromis:  "N",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "C",
      squirrelfish: "N",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "C",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# GRUNTS/SWEETLIPS
#############################################################################
Fish.create( 
      name: "Grunts/Sweetlips",
      wiki_url: 'Plectorhinchus',
      dwarf_angels: "Y", 
      large_angels: "Y", 
      anglers_frogs:  "Y", 
      anthias:  "Y", 
      basslets: "Y", 
      batfish:  "Y", 
      blennies: "C", 
      boxfish:  "Y", 
      butterflies:  "Y", 
      cardinals:  "Y", 
      chromis:  "C", 
      clownfish:  "Y", 
      damsels:  "C", 
      dartfish: "C", 
      dragonets:  "C", 
      eels: "Y", 
      filefish: "Y", 
      foxface_rabbits:  "Y", 
      gobies: "C", 
      groupers: "C",
      grunts_sweetlips: "C",
      jawfish:  "C",
      hawkfish: "C",
      hogfish:  "Y",
      lions_scorpions:  "C",
      parrotfish: "Y",
      pseudochromis:  "Y",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "C",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "C",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# JAWFISH
#############################################################################
Fish.create( 
      name: "Jawfish",
      wiki_url: 'Opistognathidae',
      dwarf_angels: "Y", 
      large_angels: "C", 
      anglers_frogs:  "N", 
      anthias:  "Y", 
      basslets: "Y", 
      batfish:  "Y", 
      blennies: "C", 
      boxfish:  "Y", 
      butterflies:  "Y", 
      cardinals:  "Y", 
      chromis:  "Y", 
      clownfish:  "Y", 
      damsels:  "Y", 
      dartfish: "Y", 
      dragonets:  "Y", 
      eels: "N", 
      filefish: "Y", 
      foxface_rabbits:  "Y", 
      gobies: "Y", 
      groupers: "N", 
      grunts_sweetlips: "C",
      jawfish:  "C",
      hawkfish: "Y",
      hogfish:  "C",
      lions_scorpions:  "N",
      parrotfish: "C",
      pseudochromis:  "Y",
      puffers:  "Y",
      seahorse_pipefish:  "C",
      sharks_rays:  "N",
      squirrelfish: "C",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# HAWKFISH
#############################################################################
Fish.create( 
      name: "Hawkfish",
      wiki_url: 'Hawkfish',
      dwarf_angels: "Y", 
      large_angels: "Y", 
      anglers_frogs:  "C", 
      anthias:  "Y", 
      basslets: "Y", 
      batfish:  "Y", 
      blennies: "Y", 
      boxfish:  "C", 
      butterflies:  "Y", 
      cardinals:  "Y", 
      chromis:  "Y", 
      clownfish:  "Y", 
      damsels:  "Y", 
      dartfish: "Y", 
      dragonets:  "Y", 
      eels: "N", 
      filefish: "Y", 
      foxface_rabbits:  "Y", 
      gobies: "Y", 
      groupers: "N", 
      grunts_sweetlips: "C", 
      jawfish:  "Y",
      hawkfish: "C",
      hogfish:  "Y",
      lions_scorpions:  "N",
      parrotfish: "Y",
      pseudochromis:  "Y",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# HOGFISH
#############################################################################
Fish.create( 
      name: "Hogfish",
      wiki_url: 'Hogfish',
      dwarf_angels: "Y", 
      large_angels: "Y", 
      anglers_frogs:  "C", 
      anthias:  "Y", 
      basslets: "C", 
      batfish:  "C", 
      blennies: "C", 
      boxfish:  "Y", 
      butterflies:  "Y", 
      cardinals:  "C", 
      chromis:  "C", 
      clownfish:  "C", 
      damsels:  "C", 
      dartfish: "C", 
      dragonets:  "C", 
      eels: "C", 
      filefish: "Y", 
      foxface_rabbits:  "Y", 
      gobies: "C", 
      groupers: "C", 
      grunts_sweetlips: "Y", 
      jawfish:  "C", 
      hawkfish: "Y",
      hogfish:  "N",
      lions_scorpions:  "C",
      parrotfish: "Y",
      pseudochromis:  "C",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "C",
      squirrelfish: "C",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# LIONS/SCORPIONS
#############################################################################
Fish.create( 
      name: "Lions/Scorpions",
      wiki_url: 'Pterois',
      dwarf_angels: "C", 
      large_angels: "Y", 
      anglers_frogs:  "Y", 
      anthias:  "C", 
      basslets: "N", 
      batfish:  "C", 
      blennies: "N", 
      boxfish:  "Y", 
      butterflies:  "C", 
      cardinals:  "N", 
      chromis:  "N", 
      clownfish:  "N", 
      damsels:  "N", 
      dartfish: "N", 
      dragonets:  "N", 
      eels: "Y", 
      filefish: "C", 
      foxface_rabbits:  "Y", 
      gobies: "N", 
      groupers: "Y", 
      grunts_sweetlips: "C", 
      jawfish:  "N", 
      hawkfish: "N", 
      hogfish:  "C",
      lions_scorpions:  "Y",
      parrotfish: "C",
      pseudochromis:  "N",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "C",
      squirrelfish: "C",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "C",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# PARROTFISH
#############################################################################
Fish.create( 
      name: "Parrotfish",
      wiki_url: 'Parrotfish',
      dwarf_angels: "Y", 
      large_angels: "Y", 
      anglers_frogs:  "C", 
      anthias:  "Y", 
      basslets: "C", 
      batfish:  "Y", 
      blennies: "C", 
      boxfish:  "Y", 
      butterflies:  "Y", 
      cardinals:  "C", 
      chromis:  "Y", 
      clownfish:  "Y", 
      damsels:  "Y", 
      dartfish: "C", 
      dragonets:  "C", 
      eels: "C", 
      filefish: "Y", 
      foxface_rabbits:  "Y", 
      gobies: "C", 
      groupers: "C", 
      grunts_sweetlips: "Y", 
      jawfish:  "C", 
      hawkfish: "Y", 
      hogfish:  "Y", 
      lions_scorpions:  "C",
      parrotfish: "Y",
      pseudochromis:  "C",
      puffers:  "Y",
      seahorse_pipefish:  "N",
      sharks_rays:  "C",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "C",
      wrasse_fish_only: "C",
      live_corals:  "N",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# PSEUDOCHROMIS
#############################################################################
Fish.create( 
      name: "Pseudochromis",
      wiki_url: 'Pseudochromis',
      dwarf_angels: "Y", 
      large_angels: "C", 
      anglers_frogs:  "N", 
      anthias:  "Y", 
      basslets: "N", 
      batfish:  "C", 
      blennies: "C", 
      boxfish:  "Y", 
      butterflies:  "Y", 
      cardinals:  "C", 
      chromis:  "Y", 
      clownfish:  "Y", 
      damsels:  "Y", 
      dartfish: "C", 
      dragonets:  "C", 
      eels: "N", 
      filefish: "C", 
      foxface_rabbits:  "Y", 
      gobies: "Y", 
      groupers: "N", 
      grunts_sweetlips: "Y", 
      jawfish:  "Y", 
      hawkfish: "Y", 
      hogfish:  "C", 
      lions_scorpions:  "N", 
      parrotfish: "C",
      pseudochromis:  "N",
      puffers:  "C",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "N",
      wrasse_reef_safe: "C",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "C",
      live_rock_sand: "Y",
      )

#############################################################################
# PUFFERS
#############################################################################
Fish.create( 
      name: "Puffers",
      wiki_url: 'Tetraodontidae',
      dwarf_angels: "Y", 
      large_angels: "Y", 
      anglers_frogs:  "C", 
      anthias:  "Y", 
      basslets: "C", 
      batfish:  "Y", 
      blennies: "Y", 
      boxfish:  "C", 
      butterflies:  "Y", 
      cardinals:  "Y", 
      chromis:  "Y", 
      clownfish:  "Y", 
      damsels:  "Y", 
      dartfish: "C", 
      dragonets:  "Y", 
      eels: "Y", 
      filefish: "Y", 
      foxface_rabbits:  "Y", 
      gobies: "Y", 
      groupers: "Y", 
      grunts_sweetlips: "Y", 
      jawfish:  "Y", 
      hawkfish: "Y", 
      hogfish:  "Y", 
      lions_scorpions:  "Y", 
      parrotfish: "Y", 
      pseudochromis:  "C",
      puffers:  "N",
      seahorse_pipefish:  "N",
      sharks_rays:  "N",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "C",
      live_corals:  "C",
      invertebrates:  "N",
      live_rock_sand: "Y"
      )

#############################################################################
# SEAHORSE/PIPEFISH
#############################################################################
Fish.create( 
      name: "Seahorse/Pipefish",
      wiki_url: 'Seahorse',
      dwarf_angels: "N", 
      large_angels: "N", 
      anglers_frogs:  "N", 
      anthias:  "N", 
      basslets: "N", 
      batfish:  "N", 
      blennies: "N", 
      boxfish:  "N", 
      butterflies:  "N", 
      cardinals:  "N", 
      chromis:  "N", 
      clownfish:  "N", 
      damsels:  "N", 
      dartfish: "C", 
      dragonets:  "Y", 
      eels: "N", 
      filefish: "N", 
      foxface_rabbits:  "N", 
      gobies: "C", 
      groupers: "N", 
      grunts_sweetlips: "N", 
      jawfish:  "C", 
      hawkfish: "N", 
      hogfish:  "N", 
      lions_scorpions:  "N", 
      parrotfish: "N", 
      pseudochromis:  "N", 
      puffers:  "N",
      seahorse_pipefish:  "Y",
      sharks_rays:  "N",
      squirrelfish: "N",
      tangs_surgeons: "N",
      triggerfish:  "N",
      wrasse_reef_safe: "N",
      wrasse_fish_only: "N",
      live_corals:  "Y",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# SHARKS/RAYS
#############################################################################
Fish.create( 
      name: "Sharks/Rays",
      wiki_url: 'Elasmobranchii',
      dwarf_angels: "N", 
      large_angels: "C", 
      anglers_frogs:  "N", 
      anthias:  "N", 
      basslets: "N", 
      batfish:  "N", 
      blennies: "N", 
      boxfish:  "N", 
      butterflies:  "N", 
      cardinals:  "N", 
      chromis:  "N", 
      clownfish:  "N", 
      damsels:  "N", 
      dartfish: "N", 
      dragonets:  "N", 
      eels: "C", 
      filefish: "N", 
      foxface_rabbits:  "C", 
      gobies: "N", 
      groupers: "C", 
      grunts_sweetlips: "C", 
      jawfish:  "N", 
      hawkfish: "N", 
      hogfish:  "C", 
      lions_scorpions:  "C", 
      parrotfish: "C", 
      pseudochromis:  "N", 
      puffers:  "N", 
      seahorse_pipefish:  "N",
      sharks_rays:  "C",
      squirrelfish: "C",
      tangs_surgeons: "C",
      triggerfish:  "N",
      wrasse_reef_safe: "N",
      wrasse_fish_only: "C",
      live_corals:  "C",
      invertebrates:  "N",
      live_rock_sand: "Y"
      )

#############################################################################
# SQUIRRELFISH
#############################################################################
Fish.create( 
      name: "Squirrelfish",
      wiki_url: 'Holocentrinae',
      dwarf_angels: "Y", 
      large_angels: "Y", 
      anglers_frogs:  "Y", 
      anthias:  "Y", 
      basslets: "Y", 
      batfish:  "Y", 
      blennies: "C", 
      boxfish:  "Y", 
      butterflies:  "C", 
      cardinals:  "C", 
      chromis:  "C", 
      clownfish:  "Y", 
      damsels:  "C", 
      dartfish: "C", 
      dragonets:  "C", 
      eels: "C", 
      filefish: "Y", 
      foxface_rabbits:  "Y", 
      gobies: "C", 
      groupers: "N", 
      grunts_sweetlips: "Y", 
      jawfish:  "C", 
      hawkfish: "Y", 
      hogfish:  "C", 
      lions_scorpions:  "C", 
      parrotfish: "Y", 
      pseudochromis:  "Y", 
      puffers:  "Y", 
      seahorse_pipefish:  "N", 
      sharks_rays:  "C",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "C",
      wrasse_reef_safe: "C",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "C",
      live_rock_sand: "Y",
      )

#############################################################################
# TANGS/SURGEONS
#############################################################################
Fish.create( 
      name: "Tangs/Surgeons",
      wiki_url: 'Acanthuridae',
      dwarf_angels: "Y", 
      large_angels: "Y", 
      anglers_frogs:  "Y", 
      anthias:  "Y", 
      basslets: "Y", 
      batfish:  "C", 
      blennies: "Y", 
      boxfish:  "Y", 
      butterflies:  "Y", 
      cardinals:  "Y", 
      chromis:  "Y",
      clownfish:  "Y", 
      damsels:  "Y", 
      dartfish: "Y", 
      dragonets:  "Y", 
      eels: "Y", 
      filefish: "Y", 
      foxface_rabbits:  "Y", 
      gobies: "Y", 
      groupers: "Y", 
      grunts_sweetlips: "Y", 
      jawfish:  "Y", 
      hawkfish: "Y", 
      hogfish:  "Y", 
      lions_scorpions:  "Y", 
      parrotfish: "Y", 
      pseudochromis:  "Y", 
      puffers:  "Y", 
      seahorse_pipefish:  "N", 
      sharks_rays:  "C", 
      squirrelfish: "Y",
      tangs_surgeons: "C",
      triggerfish:  "C",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "Y",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# TRIGGERFISH
#############################################################################
Fish.create( 
      name: "Triggerfish",
      wiki_url: 'Triggerfish',
      dwarf_angels: "C", 
      large_angels: "C", 
      anglers_frogs:  "N", 
      anthias:  "C", 
      basslets: "N", 
      batfish:  "N", 
      blennies: "C", 
      boxfish:  "C", 
      butterflies:  "C", 
      cardinals:  "N", 
      chromis:  "C", 
      clownfish:  "C", 
      damsels:  "C", 
      dartfish: "N", 
      dragonets:  "N", 
      eels: "C", 
      filefish: "N", 
      foxface_rabbits:  "C", 
      gobies: "C", 
      groupers: "C", 
      grunts_sweetlips: "C", 
      jawfish:  "C", 
      hawkfish: "C", 
      hogfish:  "C", 
      lions_scorpions:  "C", 
      parrotfish: "C", 
      pseudochromis:  "N", 
      puffers:  "C", 
      seahorse_pipefish:  "N", 
      sharks_rays:  "N", 
      squirrelfish: "C", 
      tangs_surgeons: "C",
      triggerfish:  "C",
      wrasse_reef_safe: "C",
      wrasse_fish_only: "C",
      live_corals:  "C",
      invertebrates:  "N",
      live_rock_sand: "Y"
      )

#############################################################################
# WRASSE: REEF SAFE
#############################################################################
Fish.create( 
      name: "Wrasse: Reef Safe",
      wiki_url: 'Wrasse',
      dwarf_angels: "Y", 
      large_angels: "Y", 
      anglers_frogs:  "C", 
      anthias:  "Y", 
      basslets: "Y", 
      batfish:  "Y", 
      blennies: "Y", 
      boxfish:  "Y", 
      butterflies:  "Y", 
      cardinals:  "Y", 
      chromis:  "Y", 
      clownfish:  "Y", 
      damsels:  "Y", 
      dartfish: "Y", 
      dragonets:  "Y", 
      eels: "C", 
      filefish: "Y", 
      foxface_rabbits:  "Y", 
      gobies: "Y", 
      groupers: "C", 
      grunts_sweetlips: "C", 
      jawfish:  "Y", 
      hawkfish: "Y", 
      hogfish:  "Y", 
      lions_scorpions:  "C", 
      parrotfish: "C", 
      pseudochromis:  "C", 
      puffers:  "Y", 
      seahorse_pipefish:  "N", 
      sharks_rays:  "N", 
      squirrelfish: "C", 
      tangs_surgeons: "Y", 
      triggerfish:  "C",
      wrasse_reef_safe: "C",
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# WRASSE: FISH ONLY
#############################################################################
Fish.create( 
      name: "Wrasse: Fish Only",
      wiki_url: 'Wrasse',
      dwarf_angels: "C", 
      large_angels: "Y", 
      anglers_frogs:  "C", 
      anthias:  "C", 
      basslets: "C", 
      batfish:  "C", 
      blennies: "C", 
      boxfish:  "Y", 
      butterflies:  "C", 
      cardinals:  "C", 
      chromis:  "C", 
      clownfish:  "Y", 
      damsels:  "Y", 
      dartfish: "C", 
      dragonets:  "C", 
      eels: "C", 
      filefish: "C", 
      foxface_rabbits:  "C", 
      gobies: "C", 
      groupers: "C", 
      grunts_sweetlips: "C", 
      jawfish:  "C", 
      hawkfish: "C", 
      hogfish:  "C", 
      lions_scorpions:  "C", 
      parrotfish: "C", 
      pseudochromis:  "C", 
      puffers:  "C", 
      seahorse_pipefish:  "N", 
      sharks_rays:  "C", 
      squirrelfish: "C", 
      tangs_surgeons: "Y", 
      triggerfish:  "C", 
      wrasse_reef_safe: "C",
      wrasse_fish_only: "C",
      live_corals:  "C",
      invertebrates:  "C",
      live_rock_sand: "Y"
      )

#############################################################################
# LIVE CORALS
#############################################################################
Fish.create( 
      name: "Live Corals",
      wiki_url: 'Coral',
      dwarf_angels: "C", 
      large_angels: "C", 
      anglers_frogs:  "Y", 
      anthias:  "Y", 
      basslets: "Y", 
      batfish:  "Y", 
      blennies: "Y", 
      boxfish:  "Y", 
      butterflies:  "C", 
      cardinals:  "Y", 
      chromis:  "Y", 
      clownfish:  "Y", 
      damsels:  "Y", 
      dartfish: "Y", 
      dragonets:  "Y", 
      eels: "Y", 
      filefish: "C", 
      foxface_rabbits:  "C", 
      gobies: "Y", 
      groupers: "Y", 
      grunts_sweetlips: "Y", 
      jawfish:  "Y", 
      hawkfish: "Y", 
      hogfish:  "Y", 
      lions_scorpions:  "Y", 
      parrotfish: "N", 
      pseudochromis:  "Y", 
      puffers:  "C", 
      seahorse_pipefish:  "Y", 
      sharks_rays:  "C", 
      squirrelfish: "Y", 
      tangs_surgeons: "Y", 
      triggerfish:  "C", 
      wrasse_reef_safe: "Y", 
      wrasse_fish_only: "C",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# INVERTEBRATES
#############################################################################
Fish.create( 
      name: "Invertebrates",
      wiki_url: 'Crustacean',
      dwarf_angels: "C", 
      large_angels: "C", 
      anglers_frogs:  "C", 
      anthias:  "C", 
      basslets: "Y", 
      batfish:  "Y", 
      blennies: "C", 
      boxfish:  "Y", 
      butterflies:  "C", 
      cardinals:  "C", 
      chromis:  "Y", 
      clownfish:  "Y", 
      damsels:  "Y", 
      dartfish: "Y", 
      dragonets:  "Y", 
      eels: "Y", 
      filefish: "Y", 
      foxface_rabbits:  "C", 
      gobies: "N", 
      groupers: "C", 
      grunts_sweetlips: "Y", 
      jawfish:  "C", 
      hawkfish: "C", 
      hogfish:  "Y", 
      lions_scorpions:  "C", 
      parrotfish: "C", 
      pseudochromis:  "C", 
      puffers:  "N", 
      seahorse_pipefish:  "C", 
      sharks_rays:  "N", 
      squirrelfish: "C", 
      tangs_surgeons: "Y", 
      triggerfish:  "N", 
      wrasse_reef_safe: "C", 
      wrasse_fish_only: "C", 
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )

#############################################################################
# LIVE ROCK/SAND
#############################################################################
Fish.create( 
      name: "Live Rock/Sand",
      wiki_url: 'Live_rock',
      dwarf_angels: "Y",
      large_angels: "Y",
      anglers_frogs:  "Y",
      anthias:  "Y",
      basslets: "Y",
      batfish:  "Y",
      blennies: "Y",
      boxfish:  "Y",
      butterflies:  "Y",
      cardinals:  "Y",
      chromis:  "Y",
      clownfish:  "Y",
      damsels:  "Y",
      dartfish: "Y",
      dragonets:  "Y",
      eels: "Y",
      filefish: "Y",
      foxface_rabbits:  "Y",
      gobies: "Y",
      groupers: "Y",
      grunts_sweetlips: "Y",
      jawfish:  "Y",
      hawkfish: "Y",
      hogfish:  "Y",
      lions_scorpions:  "Y",
      parrotfish: "Y",
      pseudochromis:  "Y",
      puffers:  "Y",
      seahorse_pipefish:  "Y",
      sharks_rays:  "Y",
      squirrelfish: "Y",
      tangs_surgeons: "Y",
      triggerfish:  "Y",
      wrasse_reef_safe: "Y",
      wrasse_fish_only: "Y",
      live_corals:  "Y",
      invertebrates:  "Y",
      live_rock_sand: "Y"
      )